app:
  message: "Hello, "

server:
  port: 7070
  disable-hostname-verification: true
  trust-all: true
  tls:
    # possible values REQUIRE | NONE
    client-auth: "REQUIRE"
    trust:
      pem-cert-chain-path: "certificates2/ca.crt"
    private-key:
      pem-key-path: "certificates2/server.key"
      pem-cert-chain-path: "certificates2/server.crt"
